language: python

# We need docker for our scripts that test various installations
services:
  - docker

# Allow cache of downloads
cache: pip

python:
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"

# command to install dependencies
# some are only used for travis/coveralls so we are installing them here only
#install:
#  - ./test/setup_test.sh
# command to run tests


env:
  # Python:
  - TEST_SUITE=UNIT-TEST
  # Then installations on various distro
  - TEST_SUITE=CENTOS
  - TEST_SUITE=DEBIAN
  - TEST_SUITE=FEDORA
  - TEST_SUITE=OTHER
  - TEST_SUITE=UBUNTU

before_install:
  - sudo apt-get -y install python-pycurl
  - sudo apt-get -y install python3-pycurl
  - sudo apt-get -y install python-nose
  - sudo apt-get -y install python3-nose
  - sudo apt-get -y install python-pip
  - sudo apt-get -y install python3-pip
  - sudo apt-get -y install libgnutls-dev
addons:
  apt:
    update: true

script:
  - cd test
  - chmod a+x *sh *py
  - ./test_suite.sh

# specific call to launch coverage data into coveralls.io
#after_success:
#  coveralls
